language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install codecov
  - pip install coveralls
  - pip install -r requirements.txt
script:
  coverage run -m unittest discover
after_success:
  - codecov
  - coveralls
